server:
#  port: 9090
  servlet:
    context-path: /app/api

spring:
  application:
    name: user-management
  datasource:
    url: jdbc:h2:mem:${spring.application.name}
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: org.hibernate.dialect.H2Dialect
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

# Spring Actuator Configurations
management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /admin
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  cloudfoundry:
    skip-ssl-validation: true

# Additional Application Information Configuration
info:
  app:
    name: ${spring.application.name}
    description: User management RESTful web service
    version: 1.0
    swagger-url: http://localhost:${server.port}${server.servlet.context-path}/swagger-ui.html
